### ISSUE TITLE
Stripping types from polymorphic lambda functions

### ISSUE THREAD

**Issue by alsiola** [leebyron/rollup-plugin-flow#3]
If I have a typed object with a lambda function as a value, such as:

````js
{
    propertyName: <T>(input : T[], reducer : (a : T) => number) : number => {
        // do something
    }
}
````

Then I get a failure of "Unexpected token" at the first line of code outside the object literal.  If I remove the <T>, as below, then all runs fine, but the typing no longer works.

 ````js
{
    propertyName: (input : T[], reducer : (a : T) => number) : number => {
        // do something
    }
}
````

I _think_ this is because the <T> is being interpreted as an opening JSX tag, but I'm not certain.

**Comment by amsul** [comment]
@leebyron this is still an issue. Any ideas on how we'd get around this?

@alsiola were you able to find a solution?

**Comment by alsiola** [comment]
@amsul Sorry I don't recall ever solving this, and I don't work with the flow ecosystem currently.
